apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: devlopment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: 192.168.40.138/jenkins-demo/nginx:v1
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
---
apiVersion: v1
kind: Service
metadata:
   name: demo
   namespace: devlopment
spec:
   selector:
     app: jenkins-demo
   type: NodePort
   ports:
   - port: 80
     targetPort: 80
     nodePort: 80
